apiVersion: v1

kind: PersistentVolume

metadata:
  name: myprom-pv
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv-data/prom"